export const PATHS = {
    HOME: '/',
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    FORGOT_PASSWORD: '/auth/forgot-password',
    PRODUCTS: '/products',
    PRODUCT_DETAILS: (id) => `/products/${id}`,
    CART: '/cart',
    CHECKOUT: '/checkout',
    VENDORS: '/vendors',
    ORDERS: '/orders',
    ORDER_DETAILS: (id) => `/orders/${id}`,
    VENDOR_DASHBOARD: '/vendor/dashboard',
    ADMIN_DASHBOARD: '/admin/dashboard',
    ADMIN_PRODUCTS: '/admin/products',
    ADMIN_VENDORS: '/admin/vendors',
    ADMIN_ORDERS: '/admin/orders',
    ADMIN_USERS: '/admin/users',
    ADMIN_BANNERS: '/admin/banners',
    ADMIN_CATEGORIES: '/admin/categories',
    ADMIN_REVIEWS: '/admin/reviews',
    ABOUT: '/about',
    VENDOR_LOGIN: '/vendor/login',
    ADMIN_LOGIN: '/admin/login',
    OFFERS: '/offers',
    CONTACT: '/contact',
};
